#!/bin/bash

# Install it with:
# ln -s /root/zamiel-bot/zambot /usr/local/bin/zambot

# Configuration
BOT_DIRECTORY="/root/zamiel-bot"

# Exit on errors
set -e

# Reboot the bot so that the changes take effect
"$BOT_DIRECTORY/restart.sh"
