const infoList = {
    'jud6s':           'Jud6s mod download + info: https://zamiell.github.io/jud6s/',
    'judas':           'Jud6s mod download + info: https://zamiell.github.io/jud6s/',
    'judasd6':         'Jud6s mod download + info: https://zamiell.github.io/jud6s/',
    'diversity':       'Diversity mod download + info: https://zamiell.github.io/isaac-racing-mods/',
    'divmod':          'Diversity mod download + info: https://zamiell.github.io/isaac-racing-mods/',
    'instantstart':    'Instant Start mod download + info: https://zamiell.github.io/isaac-racing-mods/',
    'instantstartmod': 'Instant Start mod download + info: https://zamiell.github.io/isaac-racing-mods/',
    'ismod':           'Instant Start mod download + info: https://zamiell.github.io/isaac-racing-mods/',
    'is':              'Instant Start mod download + info: https://zamiell.github.io/isaac-racing-mods/',
    'noreset':         'Instant Start mod download + info: https://zamiell.github.io/isaac-racing-mods/',
    'noresetmod':      'Instant Start mod download + info: https://zamiell.github.io/isaac-racing-mods/',
    'nrmod':           'Instant Start mod download + info: https://zamiell.github.io/isaac-racing-mods/',
    'nr':              'Instant Start mod download + info: https://zamiell.github.io/isaac-racing-mods/',
    'mod':             'Isaac Racing Mods download + info: https://zamiell.github.io/isaac-racing-mods/',
    'mods':            'Isaac Racing Mods download + info: https://zamiell.github.io/isaac-racing-mods/',
    'isaacmod':        'Isaac Racing Mods download + info: https://zamiell.github.io/isaac-racing-mods/',
    'isaacmods':       'Isaac Racing Mods download + info: https://zamiell.github.io/isaac-racing-mods/',
    'isaacracingmod':  'Isaac Racing Mods download + info: https://zamiell.github.io/isaac-racing-mods/',
    'isaacracingmods': 'Isaac Racing Mods download + info: https://zamiell.github.io/isaac-racing-mods/',
    'tournament':      'List/schedule of Isaac tournaments and events: http://pastebin.com/q9Y3MRdT',
    'tournaments':     'List/schedule of Isaac tournaments and events: http://pastebin.com/q9Y3MRdT',
    'lemon':           'Lemon Party League #2 info: http://www.lemonpartyleague.com/',
    'lemonparty':      'Lemon Party League #2 info: http://www.lemonpartyleague.com/',
    'lemonleague':     'Lemon Party League #2 info: http://www.lemonpartyleague.com/',
    'lpl':             'Lemon Party League #2 info: http://www.lemonpartyleague.com/',
    'iotr':            'Isaacs of the Round League info: http://isaacsoftheround.weebly.com/',
    'schedule':        'Isaacs of the Round Finals Tournament schedule: https://docs.google.com/spreadsheets/d/1Kn5xHFrHiQKDutqH3QVyqFETOfWv-pn_kR9UNIFVg7w/edit#gid=65786501',
    'bracket':         'Isaacs of the Round bracket: http://challonge.com/iotr',
    'challonge':       'Isaacs of the Round bracket: http://challonge.com/iotr',
    'tracker':         'Rebirth Item Tracker download + info: https://github.com/Hyphen-ated/RebirthItemTracker/releases',
    'itemtracker':     'Rebirth Item Tracker download + info: https://github.com/Hyphen-ated/RebirthItemTracker/releases',
    '100':             'Fully unlocked Afterbirth save download: http://www.speedrun.com/saves/fully_unlocked_afterbirth_save_5vkrx.zip',
    '100%':            'Fully unlocked Afterbirth save download: http://www.speedrun.com/saves/fully_unlocked_afterbirth_save_5vkrx.zip',
    '1001':            'Fully unlocked Afterbirth save download: http://www.speedrun.com/saves/fully_unlocked_afterbirth_save_5vkrx.zip',
    '1001%':           'Fully unlocked Afterbirth save download: http://www.speedrun.com/saves/fully_unlocked_afterbirth_save_5vkrx.zip',
    'save':            'Fully unlocked Afterbirth save download: http://www.speedrun.com/saves/fully_unlocked_afterbirth_save_5vkrx.zip',
    'savefile':        'Fully unlocked Afterbirth save download: http://www.speedrun.com/saves/fully_unlocked_afterbirth_save_5vkrx.zip',
    'srl':             'SRL tutorial video: http://bombch.us/4u | FAQ: http://www.speedrunslive.com/faq/',
    'item':            'Platinum God explains every item in the game: http://platinumgod.co.uk/',
    'items':           'Platinum God explains every item in the game: http://platinumgod.co.uk/',
    'plat':            'Platinum God explains every item in the game: http://platinumgod.co.uk/',
    'platgod':         'Platinum God explains every item in the game: http://platinumgod.co.uk/',
    'platinumgod':     'Platinum God explains every item in the game: http://platinumgod.co.uk/',
    'start':           'Item starts for racing: http://pastebin.com/mCmrYP8Q',
    'starts':          'Item starts for racing: http://pastebin.com/mCmrYP8Q',
    'discord':         'Join the Isaac racing & speedrunning Discord server: https://discord.gg/JzbhWQb',
    'faq':             'ZamielBot FAQ: http://pastebin.com/8ysF8VgX',
    'help':            'ZamielBot FAQ: http://pastebin.com/8ysF8VgX',
    'commands':        'ZamielBot FAQ: http://pastebin.com/8ysF8VgX',
};

exports.infoList = infoList;
