const infoList = {
    'jud6s':           'Racing+ is a mod for The Binding of Isaac: Afterbirth+: https://isaacracing.net',
    'judas':           'Racing+ is a mod for The Binding of Isaac: Afterbirth+: https://isaacracing.net',
    'judasd6':         'Racing+ is a mod for The Binding of Isaac: Afterbirth+: https://isaacracing.net',
    'diversity':       'Racing+ is a mod for The Binding of Isaac: Afterbirth+: https://isaacracing.net',
    'divmod':          'Racing+ is a mod for The Binding of Isaac: Afterbirth+: https://isaacracing.net',
    'instantstart':    'Racing+ is a mod for The Binding of Isaac: Afterbirth+: https://isaacracing.net',
    'instantstartmod': 'Racing+ is a mod for The Binding of Isaac: Afterbirth+: https://isaacracing.net',
    'ismod':           'Racing+ is a mod for The Binding of Isaac: Afterbirth+: https://isaacracing.net',
    'is':              'Racing+ is a mod for The Binding of Isaac: Afterbirth+: https://isaacracing.net',
    'noreset':         'Racing+ is a mod for The Binding of Isaac: Afterbirth+: https://isaacracing.net',
    'noresetmod':      'Racing+ is a mod for The Binding of Isaac: Afterbirth+: https://isaacracing.net',
    'nrmod':           'Racing+ is a mod for The Binding of Isaac: Afterbirth+: https://isaacracing.net',
    'nr':              'Racing+ is a mod for The Binding of Isaac: Afterbirth+: https://isaacracing.net',
    'mod':             'Racing+ is a mod for The Binding of Isaac: Afterbirth+: https://isaacracing.net',
    'mods':            'Racing+ is a mod for The Binding of Isaac: Afterbirth+: https://isaacracing.net',
    'isaacmod':        'Racing+ is a mod for The Binding of Isaac: Afterbirth+: https://isaacracing.net',
    'isaacmods':       'Racing+ is a mod for The Binding of Isaac: Afterbirth+: https://isaacracing.net',
    'isaacracingmod':  'Racing+ is a mod for The Binding of Isaac: Afterbirth+: https://isaacracing.net',
    'isaacracingmods': 'Racing+ is a mod for The Binding of Isaac: Afterbirth+: https://isaacracing.net',
    'tournament':      'List/schedule of Isaac tournaments and events: http://pastebin.com/q9Y3MRdT',
    'tournaments':     'List/schedule of Isaac tournaments and events: http://pastebin.com/q9Y3MRdT',
    'lemon':           'Lemon Party League #2 info: http://www.lemonpartyleague.com/',
    'lemonparty':      'Lemon Party League #2 info: http://www.lemonpartyleague.com/',
    'lemonleague':     'Lemon Party League #2 info: http://www.lemonpartyleague.com/',
    'lpl':             'Lemon Party League #2 info: http://www.lemonpartyleague.com/',
    'tracker':         'Rebirth Item Tracker download + info: https://github.com/Hyphen-ated/RebirthItemTracker/releases',
    'itemtracker':     'Rebirth Item Tracker download + info: https://github.com/Hyphen-ated/RebirthItemTracker/releases',
    'rpg':             'Fully unlocked Afterbirth save download: http://www.speedrun.com/saves/fully_unlocked_afterbirth_save_5vkrx.zip',
    'realplatinumgod': 'Fully unlocked Afterbirth save download: http://www.speedrun.com/saves/fully_unlocked_afterbirth_save_5vkrx.zip',
    '100':             'Fully unlocked Afterbirth save download: http://www.speedrun.com/saves/fully_unlocked_afterbirth_save_5vkrx.zip',
    '100%':            'Fully unlocked Afterbirth save download: http://www.speedrun.com/saves/fully_unlocked_afterbirth_save_5vkrx.zip',
    '1001':            'Fully unlocked Afterbirth save download: http://www.speedrun.com/saves/fully_unlocked_afterbirth_save_5vkrx.zip',
    '1001%':           'Fully unlocked Afterbirth save download: http://www.speedrun.com/saves/fully_unlocked_afterbirth_save_5vkrx.zip',
    '1mil':            'Fully unlocked Afterbirth save download: http://www.speedrun.com/saves/fully_unlocked_afterbirth_save_5vkrx.zip',
    '1mil%':           'Fully unlocked Afterbirth save download: http://www.speedrun.com/saves/fully_unlocked_afterbirth_save_5vkrx.zip',
    'save':            'Fully unlocked Afterbirth save download: http://www.speedrun.com/saves/fully_unlocked_afterbirth_save_5vkrx.zip',
    'savefile':        'Fully unlocked Afterbirth save download: http://www.speedrun.com/saves/fully_unlocked_afterbirth_save_5vkrx.zip',
    'srl':             'SRL tutorial video: http://bombch.us/4u | FAQ: http://www.speedrunslive.com/faq/',
    'item':            'Platinum God explains every item in the game: http://platinumgod.co.uk/',
    'items':           'Platinum God explains every item in the game: http://platinumgod.co.uk/',
    'plat':            'Platinum God explains every item in the game: http://platinumgod.co.uk/',
    'platgod':         'Platinum God explains every item in the game: http://platinumgod.co.uk/',
    'platinumgod':     'Platinum God explains every item in the game: http://platinumgod.co.uk/',
    'start':           'Item starts for racing: http://pastebin.com/mCmrYP8Q',
    'starts':          'Item starts for racing: http://pastebin.com/mCmrYP8Q',
    'discord':         'Join the Isaac racing & speedrunning Discord server: https://discord.gg/JzbhWQb',
    //'faq':             'ZamielBot FAQ: http://pastebin.com/8ysF8VgX',
    //'help':            'ZamielBot FAQ: http://pastebin.com/8ysF8VgX',
    //'commands':        'ZamielBot FAQ: http://pastebin.com/8ysF8VgX',
};
exports.infoList = infoList;
