module.exports = {
    'jud6s': 'Racing+ is a mod for The Binding of Isaac: Afterbirth+: https://isaacracing.net',
    'judas': 'Racing+ is a mod for The Binding of Isaac: Afterbirth+: https://isaacracing.net',
    'judasd6': 'Racing+ is a mod for The Binding of Isaac: Afterbirth+: https://isaacracing.net',
    'diversity': 'Racing+ is a mod for The Binding of Isaac: Afterbirth+: https://isaacracing.net',
    'divmod': 'Racing+ is a mod for The Binding of Isaac: Afterbirth+: https://isaacracing.net',
    'instantstart': 'Racing+ is a mod for The Binding of Isaac: Afterbirth+: https://isaacracing.net',
    'instantstartmod': 'Racing+ is a mod for The Binding of Isaac: Afterbirth+: https://isaacracing.net',
    'ismod': 'Racing+ is a mod for The Binding of Isaac: Afterbirth+: https://isaacracing.net',
    'is': 'Racing+ is a mod for The Binding of Isaac: Afterbirth+: https://isaacracing.net',
    'noreset': 'Racing+ is a mod for The Binding of Isaac: Afterbirth+: https://isaacracing.net',
    'noresetmod': 'Racing+ is a mod for The Binding of Isaac: Afterbirth+: https://isaacracing.net',
    'nrmod': 'Racing+ is a mod for The Binding of Isaac: Afterbirth+: https://isaacracing.net',
    'nr': 'Racing+ is a mod for The Binding of Isaac: Afterbirth+: https://isaacracing.net',
    'meme': 'ALERT! It appears that you are using the word "meme" in an incorrect manner. Note that a "meme" is NOT the same thing as a "joke" - it is colloquially used to describe a specific, shared concept that is widely known in a community. The word originated from Richard Dawkins in his 1976 book, The Selfish Gene, which showed that memes are just ideas that are subject to the same pressures and evolutionary processes that biological traits are. If you want to describe something as merely being silly, a joke, or a non-official category, then you should choose a different word. Thanks for your cooperation.',
    'mod': 'Racing+ is a mod for The Binding of Isaac: Afterbirth+: https://isaacracing.net',
    'mods': 'Racing+ is a mod for The Binding of Isaac: Afterbirth+: https://isaacracing.net',
    'isaacmod': 'Racing+ is a mod for The Binding of Isaac: Afterbirth+: https://isaacracing.net',
    'isaacmods': 'Racing+ is a mod for The Binding of Isaac: Afterbirth+: https://isaacracing.net',
    'isaacracingmod': 'Racing+ is a mod for The Binding of Isaac: Afterbirth+: https://isaacracing.net',
    'isaacracingmods': 'Racing+ is a mod for The Binding of Isaac: Afterbirth+: https://isaacracing.net',
    'tournament': 'List/schedule of Isaac tournaments and events: http://pastebin.com/q9Y3MRdT',
    'tournaments': 'List/schedule of Isaac tournaments and events: http://pastebin.com/q9Y3MRdT',
    'lemon': 'Lemon Party League #2 info: http://www.lemonpartyleague.com/',
    'lemonparty': 'Lemon Party League #2 info: http://www.lemonpartyleague.com/',
    'lemonleague': 'Lemon Party League #2 info: http://www.lemonpartyleague.com/',
    'lpl': 'Lemon Party League #2 info: http://www.lemonpartyleague.com/',
    'tracker': 'Rebirth Item Tracker download + info: https://github.com/Hyphen-ated/RebirthItemTracker/releases',
    'itemtracker': 'Rebirth Item Tracker download + info: https://github.com/Hyphen-ated/RebirthItemTracker/releases',
    'rpg': 'Fully unlocked Afterbirth save download: http://www.speedrun.com/saves/fully_unlocked_afterbirth_save_5vkrx.zip',
    'realplatinumgod': 'Fully unlocked Afterbirth save download: http://www.speedrun.com/saves/fully_unlocked_afterbirth_save_5vkrx.zip',
    '100': 'Fully unlocked Afterbirth save download: http://www.speedrun.com/saves/fully_unlocked_afterbirth_save_5vkrx.zip',
    '100%': 'Fully unlocked Afterbirth save download: http://www.speedrun.com/saves/fully_unlocked_afterbirth_save_5vkrx.zip',
    '1001': 'Fully unlocked Afterbirth save download: http://www.speedrun.com/saves/fully_unlocked_afterbirth_save_5vkrx.zip',
    '1001%': 'Fully unlocked Afterbirth save download: http://www.speedrun.com/saves/fully_unlocked_afterbirth_save_5vkrx.zip',
    '1mil': 'Fully unlocked Afterbirth save download: http://www.speedrun.com/saves/fully_unlocked_afterbirth_save_5vkrx.zip',
    '1mil%': 'Fully unlocked Afterbirth save download: http://www.speedrun.com/saves/fully_unlocked_afterbirth_save_5vkrx.zip',
    'save': 'Fully unlocked Afterbirth save download: http://www.speedrun.com/saves/fully_unlocked_afterbirth_save_5vkrx.zip',
    'savefile': 'Fully unlocked Afterbirth save download: http://www.speedrun.com/saves/fully_unlocked_afterbirth_save_5vkrx.zip',
    'srl': 'SRL tutorial video: http://bombch.us/4u | FAQ: http://www.speedrunslive.com/faq/',
    'item': 'Platinum God explains every item in the game: http://platinumgod.co.uk/',
    'items': 'Platinum God explains every item in the game: http://platinumgod.co.uk/',
    'plat': 'Platinum God explains every item in the game: http://platinumgod.co.uk/',
    'platgod': 'Platinum God explains every item in the game: http://platinumgod.co.uk/',
    'platinumgod': 'Platinum God explains every item in the game: http://platinumgod.co.uk/',
    'start': 'Item starts for racing: http://pastebin.com/mCmrYP8Q',
    'starts': 'Item starts for racing: http://pastebin.com/mCmrYP8Q',
    'troll': 'ALERT! It appears that you are using the word "troll" in an incorrect manner. The word "troll" is colloquially used to denote someone who is intentionally antogonizing other people under a guise. Typically, trolls operate obtusely such that the guise is (more or less) transparent, which invokes humor when the people being antogonized are not able to comprehend this. Note that you should NOT call someone a "troll" if they are just making a joke or merely being sarcastic. Thanks for your cooperation in using the word correctly.',
    'discord': 'Join the Isaac racing & speedrunning Discord server: https://discord.gg/JzbhWQb',
    'wiki': 'The Babies Mod info & list: https://bindingofisaacrebirth.gamepedia.com/index.php?title=User:Zamie/Co-op&profile=no',
    'baby': 'The Babies Mod info & list: https://bindingofisaacrebirth.gamepedia.com/index.php?title=User:Zamie/Co-op&profile=no',
    'babies': 'The Babies Mod info & list: https://bindingofisaacrebirth.gamepedia.com/index.php?title=User:Zamie/Co-op&profile=no',
    // 'faq': 'ZamielBot FAQ: http://pastebin.com/8ysF8VgX',
    // 'help': 'ZamielBot FAQ: http://pastebin.com/8ysF8VgX',
    // 'commands': 'ZamielBot FAQ: http://pastebin.com/8ysF8VgX',
};
